### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by larissabrazb** [ishepard/pydriller#162]
Found the following error when recursivelly using Pydriller:

> Traceback (most recent call last):
>   File "/Users/larissa/.../commits-mining.py", line 47, in <module>
>     output = get_commits_info(links)
>   File "/Users/larissa/.../commits-mining.py", line 28, in get_commits_info
>     msg = commit.msg.replace("\n", ". ").replace(",","")
>   File "/usr/local/lib/python3.9/site-packages/pydriller/domain/commit.py", line 534, in msg
>     return self._c_object.message.strip()
>   File "/usr/local/lib/python3.9/site-packages/gitdb/util.py", line 253, in __getattr__
>     self._set_cache_(attr)
>   File "/usr/local/lib/python3.9/site-packages/git/objects/commit.py", line 177, in _set_cache_
>     _binsha, _typename, self.size, stream = self.repo.odb.stream(self.binsha)
>   File "/usr/local/lib/python3.9/site-packages/git/db.py", line 42, in stream
>     hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(sha))
>   File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1090, in stream_object_data
>     cmd = self._get_persistent_cmd("cat_file_all", "cat_file", batch=True)
>   File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1056, in _get_persistent_cmd
>     cmd = self._call_process(cmd_name, *args, **options)
>   File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1011, in _call_process
>     return self.execute(call, **exec_kwargs)
>   File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 724, in execute
>     proc = Popen(command,
>   File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1722, in _execute_child
>     errpipe_read, errpipe_write = os.pipe()

**OS Version:** MacOS 10.15.7
**Python:** 3.9

**Comment by ishepard** [comment]
Hi @larissabrazb! 

This doesn't seem to be related to Pydriller. Can you post a small snippet on how to reproduce the error? I'll double check if something is wrong 😄 
Thanks!

**Comment by zackcglee** [comment]
Thank you for your wonderful work.

I am experiencing the same error on pydriller 1.15.2v.
has this been fixed on the recent version?

This occurs when pydriller is recursively called.

```
Traceback (most recent call last):
  File "/home/leechanggong/.local/lib/python3.6/site-packages/pydriller/utils/conf.py", line 176, in get_ending_commit
    return self.get("git_repo").get_commit(to_commit).hash
  File "/home/leechanggong/.local/lib/python3.6/site-packages/pydriller/git_repository.py", line 143, in get_commit
    gp_commit = self.repo.commit(commit_id)
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/repo/base.py", line 480, in commit
    return self.rev_parse(str(rev) + "^0")
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/repo/fun.py", line 213, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/repo/fun.py", line 150, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/objects/base.py", line 64, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/db.py", line 37, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/cmd.py", line 1067, in get_object_header
    cmd = self._get_persistent_cmd("cat_file_header", "cat_file", batch_check=True)
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/cmd.py", line 1050, in _get_persistent_cmd
    cmd = self._call_process(cmd_name, *args, **options)
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/leechanggong/.local/lib/python3.6/site-packages/git/cmd.py", line 732, in execute
    **subprocess_kwargs
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1254, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```

The identical error occurs in both Ubuntu 18.04 and Mac OS 12.4.

If this issue has not been touched, I will try to reproduce the error.
I am not 100% sure where files are not being closed yet, so I am not also sure if this is really from pyszz.

Thank you

**Comment by zackcglee** [comment]
This error doesn't seem to occur in the latest version.

**Comment by FlickerSoul** [comment]
I am having the same issue on MacOS. This seems to be an issue with the git library which didn't close the file descriptors for subprocesses?

```text
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[2], line 6
      3 newest_commit = list(pydriller.Repository(full_path).traverse_commits())[-1]
      4 result = defaultdict(deque)
----> 6 traverse_commit(full_path, newest_commit, result, {})

Cell In[1], line 62, in traverse_commit(path, commit, all_java_files, to_add_files)
     56     traverse_queue.append(
     57         (next(pydriller.Repository(path, single=parent).traverse_commits()), str(index) + branch)
     58     )
     60 commit_index = (commit_hash, commit_time)
---> 62 for commit_file in reversed(commit_to_analyze.modified_files):
     63     if commit_file.filename.endswith(".java"):
     64         # if it's a java file
     65         match commit_file.change_type:

File ~/Library/Caches/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/pydriller/domain/commit.py:772, in Commit.modified_files(self)
    768     options["w"] = True
    770 if len(self.parents) == 1:
    771     # the commit has a parent
--> 772     diff_index: Any = self._c_object.parents[0].diff(
    773         other=self._c_object, paths=None, create_patch=True, **options
    774     )
    775 elif len(self.parents) > 1:
    776     # if it's a merge commit, the modified files of the commit are the
    777     # conflicts. This because if the file is not in conflict,
   (...)
    784     # d = c_git.diff_tree("--cc", commit.hexsha, '-r', '--abbrev=40',
    785     #                     '--full-index', '-M', '-p', '--no-color')
    786     diff_index = []

File ~/Library/Caches/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/git/diff.py:188, in Diffable.diff(self, other, paths, create_patch, **kwargs)
    185 # END paths handling
    187 kwargs["as_process"] = True
--> 188 proc = diff_cmd(*self._process_diff_args(args), **kwargs)
    190 diff_method = Diff._index_from_patch_format if create_patch else Diff._index_from_raw_format
    191 index = diff_method(self.repo, proc)

File ~/Library/Caches/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/git/cmd.py:736, in Git.__getattr__.<locals>.<lambda>(*args, **kwargs)
    734 if name[0] == "_":
    735     return LazyMixin.__getattr__(self, name)
--> 736 return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)

File ~/Library/Caches/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/git/cmd.py:1316, in Git._call_process(self, method, *args, **kwargs)
   1313 call.append(dashify(method))
   1314 call.extend(args_list)
-> 1316 return self.execute(call, **exec_kwargs)

File ~/Library/Caches/pypoetry/virtualenvs/py3.12/lib/python3.12/site-packages/git/cmd.py:988, in Git.execute(self, command, istream, with_extended_output, with_exceptions, as_process, output_stream, stdout_as_string, kill_after_timeout, with_stdout, universal_newlines, shell, env, max_chunk_size, strip_newline_in_stdout, **subprocess_kwargs)
    986 try:
    987     with maybe_patch_caller_env:
--> 988         proc = Popen(
    989             command,
    990             env=env,
    991             cwd=cwd,
    992             bufsize=-1,
    993             stdin=istream or DEVNULL,
    994             stderr=PIPE,
    995             stdout=stdout_sink,
    996             shell=shell,
    997             close_fds=is_posix,  # unsupported on windows
    998             universal_newlines=universal_newlines,
    999             creationflags=PROC_CREATIONFLAGS,
   1000             **subprocess_kwargs,
   1001         )
   1002 except cmd_not_found_exception as err:
   1003     raise GitCommandNotFound(redacted_command, err) from err

File ~/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py:1026, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize, process_group)
   1022         if self.text_mode:
   1023             self.stderr = io.TextIOWrapper(self.stderr,
   1024                     encoding=encoding, errors=errors)
-> 1026     self._execute_child(args, executable, preexec_fn, close_fds,
   1027                         pass_fds, cwd, env,
   1028                         startupinfo, creationflags, shell,
   1029                         p2cread, p2cwrite,
   1030                         c2pread, c2pwrite,
   1031                         errread, errwrite,
   1032                         restore_signals,
   1033                         gid, gids, uid, umask,
   1034                         start_new_session, process_group)
   1035 except:
   1036     # Cleanup if the child failed starting.
   1037     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File ~/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py:1849, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session, process_group)
   1844 orig_executable = executable
   1846 # For transferring possible exec failure from child to parent.
   1847 # Data format: "exception name:hex errno:description"
   1848 # Pickle is not used; it is complex and involves memory allocation.
-> 1849 errpipe_read, errpipe_write = os.pipe()
   1850 # errpipe_write must not be in the standard io 0, 1, or 2 fd range.
   1851 low_fds_to_close = []

OSError: [Errno 24] Too many open files
```
