### ISSUE TITLE
GitCommandError when traversing commits on an non-default branch

### ISSUE THREAD

**Issue by stefanodallapalma** [ishepard/pydriller#181]
**Describe the bug**
Traversing commits using the parameter `only_in_branch` with a value different from the default branch generates the following error:

```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list --reverse <branch> --
  stderr: 'fatal: bad revision '<branch>'
``` 

**To Reproduce:**

```python
for commit in Repository('https://github.com/ishepard/pydriller.git', only_in_branch='pydriller-pygit2').traverse_commits():
    print(commit.hash)
```

**Output:**
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/path/to/my/project/venv/lib/python3.8/site-packages/pydriller/repository.py", line 223, in traverse_commits
    commits_list = list(git.get_list_commits(rev, **kwargs))
  File "/path/to/my/project/venv/lib/python3.8/site-packages/pydriller/git.py", line 117, in get_list_commits
    for commit in self.repo.iter_commits(rev=rev, **kwargs):
  File "/path/to/my/project/venv/lib/python3.8/site-packages/git/objects/commit.py", line 312, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/path/to/my/project/venv/lib/python3.8/site-packages/git/util.py", line 369, in finalize_process
    proc.wait(**kwargs)
  File "/path/to/my/project/venv/lib/python3.8/site-packages/git/cmd.py", line 450, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list --reverse pydriller-pygit2 --
  stderr: 'fatal: bad revision 'pydriller-pygit2'
```

**Version:**
 PyDriller2.0 on Ubuntu 20.10

**Comment by ishepard** [comment]
Hi @stefanodallapalma!

It looks to me that git is returning an error, 
```
stderr: 'fatal: bad revision 'pydriller-pygit2'
```
This means that the branch doesn't exist. Can you run the command locally? `git rev-list --reverse pydriller-pygit2 --`

**Comment by ishepard** [comment]
My 2 cents on this is that you need to put `origin/` before the branch name, since it's remote.

**Comment by stefanodallapalma** [comment]
Hi @ishepard,
indeed, it works with origin/, thank you. I don't know if this is something that you would handle in pydriller. Anyway, I think it's worth to add that info in the parameter description for the sake of documentation.

**Comment by ishepard** [comment]
Awesome 😄 
Yeah this is not strictly related to pydriller, it's more how git displays branch names. But yeah, maybe we should point it out to use the real git name in the docs.
