### ISSUE TITLE
Accessing 'modified_files' causes 'AttributeError: 'Tree' object has no attribute '_name''

### ISSUE THREAD

**Issue by SirLich** [ishepard/pydriller#276]
**System Information**
 - git: 2.41.0.windows.2
 - pydriller: pydriller-2.5

**Describe the bug**

Accessing 'modified_files' causes 'AttributeError: 'Tree' object has no attribute '_name''. 

**To Reproduce**

Example:

```py
    repo : drill.Repository = drill.Repository(REPO_PATH, from_commit=FROM, to_commit=TO)

    for commit in repo.traverse_commits():
        print(commit.modified_files)
```

I know printing `modified_files` isn't the most useful thing to do, but this is the simplest repro I could find. 

Stack trace:

```
Traceback (most recent call last):
  File "C:\git\test\test.py", line 22, in <module>
    main()
  File "C:\git\test\test.py", line 18, in main
    print(commit.modified_files)
  File "C:\git\test\env\lib\site-packages\pydriller\domain\commit.py", line 729, in modified_files
    diff_index: Any = self._c_object.parents[0].diff(
  File "C:\git\test\env\lib\site-packages\git\diff.py", line 191, in diff
    index = diff_method(self.repo, proc)
  File "C:\git\test\env\lib\site-packages\git\diff.py", line 544, in _index_from_patch_format
    Diff(
  File "C:\git\test\env\lib\site-packages\git\diff.py", line 353, in __init__
    for submodule in repo.submodules:
  File "C:\git\test\env\lib\site-packages\git\repo\base.py", line 422, in submodules
    return Submodule.list_items(self)
  File "C:\git\test\env\lib\site-packages\git\util.py", line 1189, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "C:\git\test\env\lib\site-packages\git\objects\submodule\base.py", line 1406, in iter_items
    sm._name = n
AttributeError: 'Tree' object has no attribute '_name'
```

**OS Version:**
Windows

**Comment by ishepard** [comment]
Hi! Can you send me the entire command you use? The repo, from commit and to commit. 

There are many tests that access the commit object and they are all passing, so I think it's something related to the repo you are trying to analyze.

**Comment by a-y-f** [comment]
Maybe you should try pydriller2.4.1
just run `python -m pip install pydriller==2.4.1`, then try your code again.
